BEGIN;

CREATE TABLE IF NOT EXISTS ascii_outputs (
    id UUID PRIMARY KEY NOT NULL,
    user_id UUID NOT NULL,
    input_text TEXT NOT NULL,
    font TEXT NOT NULL,
    ascii_text TEXT NOT NULL,
    downloaded_as_image BOOLEAN DEFAULT FALSE,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY(user_id) REFERENCES users(id) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS font_idx ON ascii_outputs(font);

ALTER TABLE ascii_outputs ALTER COLUMN created_at SET NOT NULL;
ALTER TABLE ascii_outputs ALTER COLUMN created_at SET DEFAULT CURRENT_TIMESTAMP;

COMMIT;